version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: centro_control_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sistema_personal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: sistema_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/sistema_personal
    depends_on:
      - db

volumes:
  postgres_data: